GET http://localhost:3001/api/notes

###

GET http://localhost:3001/api/notes/64d67f3cc3819350a55c457e

###
DELETE http://localhost:3001/api/notes/64d67f3cc3819350a55c457e

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "REST client is good for testing backend",
  "important": false
}

###
PUT http://localhost:3001/api/notes/64d608e9a73b4fe0953a6a99
Content-Type: application/json

{
  "content": "CSS is easy",
  "important": false
}