GET http://localhost:3001/api/notes

###

GET http://localhost:3001/api/notes/64d539a0eb03130ae4935071

###
DELETE http://localhost:3001/api/notes/2

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Postman is good for testing backend",
  "important": false
}

###
PUT http://localhost:3001/api/notes/64d608e9a73b4fe0953a6a99
Content-Type: application/json

{
  "content": "Css is easy",
  "important": true
}